ARDUINO_DIR = /home/marek/src/arduino-1.0

TARGET       = geiger1
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

ARDUINO_LIBS = LiquidCrystal
AVR_TOOLS_PATH = /usr/bin
AVRDUDE_CONF   = /etc/avrdude.conf

PDEHEADER     = \\\#include \"Arduino.h\"

include /home/marek/src/arduino-mk-0.6/Arduino.mk
