#!/bin/sh

IFNO=`echo $IFNAME|tr -dc "[0-9]"`

IFNOP=$((1+$IFNO))

ip -f inet6 address add 2001:470:926a:$IFNOP::1/64 dev $IFNAME

/etc/init.d/radvd restart
sleep 0.5
# Second restart required. That way we get default route for ipv6 on mac.
# To get ipv6 working on Mac you need to run:
#     sysctl -w net.inet6.ip6.accept_rtadv=1
/etc/init.d/radvd restart

