ARDUINO_DIR = /home/marek/src/arduino-1.0

TARGET       = lilypad
BOARD_TAG    = lilypad328
ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = Wire Wire/utility
AVR_TOOLS_PATH = /usr/bin
AVRDUDE_CONF   = /etc/avrdude.conf


include /home/marek/src/arduino-mk-0.8/Arduino.mk
