USER_LIB_PATH=$(HOME)/arduino

ARDUINO_DIR = $(HOME)/arduino/arduino-1.0.5


#TARGET       = lilypad
#BOARD_TAG    = lilypad328

BOARD_TAG    = nano328

ARDUINO_PORT = /dev/ttyUSB0

ARDUINO_LIBS = Wire Wire/utility Adafruit_NeoPixel
AVR_TOOLS_PATH = /usr/bin
AVRDUDE_CONF   = /etc/avrdude.conf


include $(HOME)/arduino/arduino-mk/Arduino.mk
