ARDUINO_DIR = /home/marek/src/arduino-1.0

TARGET       = temp
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyACM0

ARDUINO_LIBS =
AVR_TOOLS_PATH = /usr/bin
AVRDUDE_CONF   = /etc/avrdude.conf


include /home/marek/src/arduino-mk-0.8/Arduino.mk
